amadeus/amadeus/amadeus/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('courses.urls', namespace = 'courses')),
    url(r'^login/$', auth_views.login, {'template_name':'accounts/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page':'index'},name='logout'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
]

amadeus/amadeus/core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^$', views.index, name='index'),
]

amadeus/amadeus/courses/urls.py
from django.conf.urls import url 

from . import views



urlpatterns = [
	url(r'^cursos/$', views.IndexView.as_view(), name='index'),
	url(r'^cursos/(?P<slug>([\w_-]+))/$', views.detailView.as_view(), name='details'),
	url(r'^categorias/([\w_-]+)/$', views.category, name='categories'),
	url(r'^create/curso$', views.CreateView.as_view(), name='create'),
	url(r'^create/module$', views.CreateModuleView.as_view(), name='create_module'),
	url(r'^create/categoria$', views.CreateCategoryView.as_view(), name='create_category')
]

amadeus/amadeus/courses/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _
import datetime


class Category(models.Model):
   name = models.CharField(_('Name'), max_length=100)
   slug = models.SlugField(_('Identifier'), max_length=100)

class Course(models.Model):

      name = models.CharField('Name', max_length=100) #VARCHAR2, precisa ter o limitante
      slug = models.SlugField('Identifier', max_length=100, unique=True)
      goals = models.TextField('Objectives', blank=True) #neste caso não preciso setar limite para o campo
      programa = models.TextField('Program',blank=True)
      is_approved = models.BooleanField('approved', default=False, blank=True)
      category = models.ForeignKey(Category, verbose_name='Categoria')
      limit = models.IntegerField('Student_Limits',default=0)
      subscription_start = models.DateTimeField(blank=True, null = True)
      subscription_finish = models.DateTimeField(blank=True, null = True)
      start_date = models.DateTimeField(blank=True, null = True)
      end_date = models.DateField(blank=True, null=True)
      image = models.ImageField(upload_to='imagens/', blank=True)



      
class Module(models.Model):

   name = models.CharField('Name', max_length = 100)
   slug = models.SlugField('Identifier', max_length = 100)
   course = models.ForeignKey(Course, on_delete= models.CASCADE,verbose_name='curso')
   visible = models.BooleanField('Visible', default=False)
   description = models.TextField('Description', blank=True)

class HomeWork(models.Model):
   name = models.CharField('Name', max_length=50)
   slug = models.SlugField('Identifier', max_length=50)

amadeus/amadeus/courses/forms.py
from .models import Course, Category, Module
from django import forms

class createCourseForm(forms.ModelForm):
	"""def __init__(self, *args, **kwargs):
		super(createCourseForm, self).__init__(*args, **kwargs)"""
	

	class Meta:
		model = Course
		fields = ('name','slug','is_approved', 'category') #I am able to set which fields I want


class createCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name','slug')
    
class createModuleForm(forms.ModelForm):
	class Meta:
		model = Module
		fields = ('name','slug','course','visible','description')

amadeus/amadeus/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Category, Course, Module
from .forms import createCourseForm, createModuleForm, createCategoryForm

from rolepermissions.verifications import has_permission
from django.views import generic
# Create your views here.

class IndexView(generic.ListView):

	queryset = Course.objects.filter(is_approved=True)
	template_name = 'courses/index.html'
	context_object_name = 'courses'
	paginate_by = 3


class ListModuleView(generic.ListView):

	template_name = 'courses/list_module.html'
	paginate_by = 2
	context_object_name = 'modules'

	def get_queryset(self, slug):
	    queryset = Module.objects.filter(course__slug=slug)
	    return queryset

	def get(self, request, *args, **kwargs):
	    self.object_list = self.get_queryset(request.slug)
	    allow_empty = self.get_allow_empty()
	    if not allow_empty:
	        # When pagination is enabled and object_list is a queryset,
	        # it's better to do a cheap query than to load the unpaginated
	        # queryset in memory.
	        if (self.get_paginate_by(self.object_list) is not None
	                and hasattr(self.object_list, 'exists')):
	            is_empty = not self.object_list.exists()
	        else:
	            is_empty = len(self.object_list) == 0
	        if is_empty:
	            raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.")
	                    % {'class_name': self.__class__.__name__})
	    context = self.get_context_data()
	    return self.render_to_response(context)


class detailView(generic.DetailView):
	model = Course

	template_name = "courses/details.html"
	
	def get_context_data(self, **kwargs):
		print(self.kwargs)
		context = {}
		course = get_object_or_404(Course, slug=self.kwargs['slug'])
		context['course'] = course
		context['complement_name'] = course.name
		return context


class ListByCategory(generic.ListView):

	template_name = 'courses/category.html'
	context_object_name = 'courses'
	paginate_by = 4

def category(request, slug='python'):
	context = {}
	category = get_object_or_404(Category, slug=slug)
	context['category'] = category
	#context['courses'] = Course.objects.filter(category=category)
	context['courses'] = category.course_set.filter(is_approved=True)
	return render(request, 'courses/category.html', context)


class CreateView(generic.CreateView):
	model = Course
	fields = ('name','slug','is_approved', 'category')
	

	def post(self, request):
		context = {}
		create_course = createCourseForm(data=request.POST)
		if create_course.is_valid():
			new_course = create_course.save(commit=False) #So it's not save right now
			new_course.save() #now it was actually saved
			context['success'] = True
			context['create_course_form'] = createCourseForm()
			context['course_name'] = new_course.name

		return render(request, 'courses/add_course.html', context)

	def get(self, request):
		context = {}
		context['create_course_form'] = createCourseForm()
		return render(request, 'courses/add_course.html', context)

class CreateModuleView(generic.CreateView):
	model = Module
	fields = ('name','slug','course','visible','description')

	def post(self, request):
		context = {}
		create_module = createModuleForm(data= request.POST)
		if create_module.is_valid():
			new_module = create_module.save(commit=False) #don't save to the database yet
			new_module.save()
			context['success'] = True
			context['create_module_form'] = createModuleForm()
			context['module_name'] = new_module.name

		return render(request,'courses/add_module.html',context)

	def get(self, request):
		context = {}
		context['create_module_form'] = createModuleForm()
		return render(request,'courses/add_module.html',context)


class CreateCategoryView(generic.CreateView):
	model = Module
	fields = ['name','slug']

	def post(self, request):
		context = {}
		create_category = createCategoryForm(data= request.POST)
		if create_category.is_valid():
			new_category = create_category.save(commit=False) #don't save to the database yet
			new_category.save()
			context['success'] = True
			context['create_category_form'] = createCategoryForm()
			context['module_name'] = new_category.name

		return render(request,'courses/add_category.html',context)

	def get(self, request):
		context = {}
		context['create_category_form'] = createCategoryForm()
		return render(request,'courses/add_category.html.html',context)

amadeus/amadeus/courses/templates/courses/add_category.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
	
	{% if success %}
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h3 class="panel-title">Cadastro foi um sucesso!</h3>
		  </div>
		  <div class="panel-body">
		    Categoria {{category_name}} foi criado com sucesso
		  </div>
		</div>
	{% endif %}
	<form class="form-horizontal" method="POST">
		 {% for field in create_category_form  %}
		 	<div class="form-group">
		 	<label class="col-lg-2 control-label">{{field.label }}</label>
		 	<div class="col-lg-10">
		 		{%render_field field class+="form-control"%}
		 	</div>
		 	</div>
		 {% endfor %}
		 <div class="form-group">
	      <div class="col-lg-10 col-lg-offset-2">
	        <button type="reset" class="btn btn-default">Cancel</button>
	        <button type="submit" class="btn btn-primary">Submit</button>
	      </div>
	    </div>
	    {% csrf_token %}
	</form>
{% endblock content %}

amadeus/amadeus/courses/templates/courses/add_course.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
	
	{% if success %}
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h3 class="panel-title">Cadastro foi um sucesso!</h3>
		  </div>
		  <div class="panel-body">
		    Curso {{course_name}} foi criado com sucesso
		  </div>
		</div>
	{% endif %}
	<form class="form-horizontal" method="POST">
		 {% for field in create_course_form  %}
		 	<div class="form-group">
		 	<label class="col-lg-2 control-label">{{field.label }}</label>
		 	<div class="col-lg-10">
		 		{%render_field field class+="form-control"%}
		 	</div>
		 	</div>
		 {% endfor %}
		 <div class="form-group">
	      <div class="col-lg-10 col-lg-offset-2">
	        <button type="reset" class="btn btn-default">Cancel</button>
	        <button type="submit" class="btn btn-primary">Submit</button>
	      </div>
	    </div>
	    {% csrf_token %}
	</form>
{% endblock content %}

amadeus/amadeus/courses/templates/courses/add_module.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load i18n %}
{% block content %}
	
	{% if success %}
		<div class="panel panel-success">
		  <div class="panel-heading">
		    <h3 class="panel-title"> {% trans "Register made with success!" %}</h3>
		  </div>
		  <div class="panel-body">
		    {% trans "Module {{modulo_name}} was created successfully" %}
		  </div>
		</div>
	{% endif %}
	<form class="form-horizontal" method="POST">
		 {% for field in create_module_form  %}
		 	<div class="form-group">
		 	<label class="col-lg-2 control-label">{{field.label }}</label>
		 	<div class="col-lg-10">
		 		{%render_field field class+="form-control"%}
		 	</div>
		 	</div>
		 {% endfor %}
		 <div class="form-group">
	      <div class="col-lg-10 col-lg-offset-2">
	        <button type="reset" class="btn btn-default">{% trans "Cancel" %}</button>
	        <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
	      </div>
	    </div>
	    {% csrf_token %}
	</form>
{% endblock content %}

amadeus/amadeus/courses/templates/courses/category.html
{% extends "base.html" %}
{% block content %}
	{% for course in courses %}
		<div class="jumbotron">
		  <h1>{{course.name}}</h1>
		  <p>Inscrições começam: {{course.subscription_start|date:"d/m/Y"|default:"Não definida"}}</p>
		  <p><a href="{% url 'courses:details' course.slug %}" class="btn btn-primary btn-md">Aprenda mais</a></p>
		</div>
	{% endfor %}

{% endblock content %}	

amadeus/amadeus/courses/templates/courses/details.html
{% extends 'base.html' %}

{% load modellist %}
{% block content %}
<div class="course-info col-md-8">
	<h1>{{ course.name }}</h1>
	<p class="lead">
	  <strong>Categoria</strong>: {{ course.category.name }}<br>
	  <strong>Objetivos</strong>: {{ course.Objetivos }}<br>
	  <strong>Programa</strong>: {{ course.programa }}<br>

	  <strong>Início do cursos</strong>: {{ course.start_date|date:"d/m/Y"|default:"Não definida" }}<br>
	  <strong>Fim do curso</strong>: {{ course.end_date|date:"d/m/Y"|default:"Não definida" }}<br>
	  
	</p>
	{% module_list request course.slug %}
	<!--{% include "courses/list_module.html" %}-->

</div>

{{ course.description|linebreaks }}
{% endblock %}

amadeus/amadeus/courses/templates/courses/index.html
{% extends "base.html" %}

{% block content %}

	{% for course in courses %}
		<div class="jumbotron">
		  <h1>{{course.name}}</h1>
		  <p>Inscrições começam: {{course.subscription_start|date:"d/m/Y"|default:"Não definida"}}</p>
		  <p><a href="{% url 'courses:categories' course.category.slug %}"><span class="label label-info"> Categoria: {{course.category.name}} </span></p>
		  <p><a href="{% url 'courses:details' course.slug %}" class="btn btn-primary btn-md">Aprenda mais</a></p>
		</div>


		<!--<h2>{{course.name}}</h2>
		<p> Inscrições começam: {{course.subscription_start|date:"d/m/Y"|default:"Não definida"}} </p>
		<ul>
			<span class="label label-info"> Categoria: {{course.category.name}} </span>
		</ul>-->
	{% endfor %}
		{% if is_paginated %} 
		<div class="text-center">
			<ul class="pagination ">

				{% if page_obj.has_previous %}
                <li>
                	<a href="/cursos/?page={{ page_obj.previous_page_number }}">{{page_obj.previous_page_number}}</a>
                </li>
                {% endif %}
                <li class="active">
                	<a href="#">{{page_obj.number}}</a>
                </li>
               
                {% if page_obj.has_next %}
                <li>    
                	<a href="/cursos/?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a> </li>
                {% endif %}
			</ul>
		</div>
			
		{% endif %}
{% endblock %}

amadeus/amadeus/courses/templates/courses/list_module.html
<h2> Módulos </h2>
	<div class="">
	{% for module in modules %}

		<div class="panel panel-info">
		  	<div class="panel-heading">
		    	<h3 class="panel-title">{{ module.name }}</h3>
		  	</div>
		  	<div class="panel-body">
		    	{{ module.description }} <br>
				{{ module.visible }} <br>
		  	</div>
			<div class="panel-footer">
		  	<div class="progress">
  				<div class="progress-bar progress-bar-success" style="width: 40%"></div>
			</div>
			</div>
		</div>

	{% endfor %}

		{% if is_paginated %} 
		<div class="text-center">
			<ul class="pagination ">

				{% if page_obj.has_previous %}
                <li>
                	<a href="/cursos/?page={{ page_obj.previous_page_number }}">{{page_obj.previous_page_number}}</a>
                </li>
                {% endif %}
                <li class="active">
                	<a href="#">{{page_obj.number}}</a>
                </li>
               
                {% if page_obj.has_next %}
                <li>    
                	<a href="/cursos/?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a> </li>
                {% endif %}
			</ul>
		</div>
			
		{% endif %}
	</div>