amadeus/amadeus/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^edit/$',views.edit_user,name='edit_user'),
	url(r'^register/$', views.RegistrationView.as_view(), name='register_user')
]

amadeus/amadeus/amadeus/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('courses.urls', namespace = 'courses')),
    url(r'^login/$', auth_views.login, {'template_name':'accounts/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page':'index'},name='logout'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
]

amadeus/amadeus/core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^$', views.index, name='index'),
]

amadeus/amadeus/amadeus/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
   
    {% if complement_name %}
      <title>Amadeus - {{ complement_name }}</title>
    {% else %}
      <title>Amadeus</title>
    {% endif %}
    
   

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>
     <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Amadeus</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'courses:index' %}"> {% trans "Courses" %} <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
       
      </ul>
      <ul class="nav navbar-nav navbar-right">
       
        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">{% trans "Login" %}</a></li>
        <li><a href="{% url 'accounts:register_user' %}">{% trans "Register" %} </a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

    <div class="container" >

      <div class="starter-template">
        {% block content %}
        
       	{% endblock %}
      </div>

    </div>
  </body>
</html>

amadeus/amadeus/amadeus/templates/form.html
{% load widget_tweaks %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    {{ error }}
</div>
{% endfor %}
{% for field in form %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.auto_id }}" class="col-sm-4 control-label">{{ field.label }}</label>
    <div class="col-sm-8">
      {% render_field field class='form-control' %}
      {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
</div>
{% endfor %}